version: '2.4'
services:

    traefik:
        image: traefik:1.7.24-alpine
        restart: always
        command:
            - --docker
            - --logLevel=INFO
            - --defaultentrypoints=http,https
            - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
            - "--entryPoints=Name:https Address::443 TLS"
            - --insecureskipverify=true
            - --acme
            - --acme.storage=/traefik-data/acme.json
            - --acme.acmelogging
            - --acme.entrypoint=https
            - --acme.httpChallenge.entrypoint=https
            - --acme.email=ivan.todorovich@gmail.com
            - --acme.onhostrule=true
        stdin_open: true
        tty: true
        ports:
            - 8000:8080/tcp
            - 80:80/tcp
            - 443:443/tcp
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
            - traefik:/traefik-data

    db:
        image: postgres:10.6
        restart: always
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - db:/var/lib/postgresql/data/pgdata

    odoo:
        image: ivantodorovich/odoo-saas:12.0
        restart: always
        tty: true
        stdin_open: true
        environment:
            ADMIN_PASSWORD: 123456
            PGDATABASE: odoo
            WAIT_PG: 'true'
            LIST_DB: 'true'
            UNACCENT: 'true'
            LOG_LEVEL: 'info'
            MAX_CRON_THREADS: 1
            WORKERS: 4
            PROXY_MODE: 'true'

        volumes:
            - ./repositories:/home/odoo/custom/repositories:rw,z
            - filestore:/home/odoo/data
            # Timezone from host
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

        depends_on:
            - db

        labels:
            traefik.odoo.frontend.rule: Host:odoo.example.com
            traefik.longpolling.frontend.rule: Host:odoo.example.com;PathPrefix:/longpolling/
            traefik.enable: 'true'
            traefik.port: '8069'
            traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
            traefik.backend.loadbalancer.method: drr
            traefik.backend.loadbalancer.stickiness: 'true'
            traefik.odoo.frontend.redirect.replacement: ''
            traefik.odoo.frontend.redirect.permanent: 'true'
            traefik.odoo.frontend.redirect.regex: ''
            traefik.odoo.port: '8069'
            traefik.longpolling.frontend.redirect.replacement: ''
            traefik.longpolling.frontend.redirect.permanent: 'true'
            traefik.longpolling.frontend.redirect.regex: ''
            traefik.longpolling.port: '8072'

volumes:
    db:
    filestore:
    traefik:
